name: Activecell Branding
markdown: redcarpet
pygments: true

source: ./
destination: ./_gh_pages
exclude: [".git", "sass", "_assets.yaml", "_config.yaml", "Gemfile", "Gemfile.lock", "Guardfile", "Procfile", "README.md", "scripts"]

# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty


current_version: 0.0.0
repo: https://github.com/activecell/activecell-branding