#!/usr/bin/env bash 

log git checkout master
git add -A
git status -s | git commit -F-
git push origin master || exit

jekyll build || exit

rm -rf /tmp/_site/
cp -r _site/. /tmp/_site/

log git checkout gh-pages

cp -r /tmp/_site/ . 
rm -rf /tmp/_site/

git add -A
git status -s | git commit -F-
git push origin gh-pages --force || exit
log git checkout master