#!/usr/bin/env bash 

git checkout master

jekyll build || exit

rm -rf /tmp/_gh_pages/
cp -r _gh_pages/. /tmp/_gh_pages/

git checkout gh-pages

rm -rf *
cp -r /tmp/_gh_pages/. . 
rm -rf /tmp/_gh_pages/

git add --all
git commit -am 'Generating site'
git push origin gh-pages --force || exit
git checkout master