#!/usr/bin/env bash 

git checkout master
git add -A
git status -s | git commit -F-
git push origin master || exit

jekyll build || exit

rm -rf /tmp/_site/
cp -r _site/. /tmp/_site/

git checkout gh-pages

rm -rf *
cp -r /tmp/_site/. . 
rm -rf /tmp/_site/

git add -A
git status -s | git commit -F-
git push origin gh-pages --force || exit
git checkout master